# Generated by Django 3.0.3 on 2020-03-11 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200311_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must have exactly 10 digits.', regex='[0-9]{10}')]),
        ),
    ]
