# Generated by Django 3.0.3 on 2020-03-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='building',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
