# Generated by Django 3.0.3 on 2020-03-11 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200311_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='building',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must have exactly 10 digits.', regex='[0-9]{10}')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street',
            field=models.CharField(default='', max_length=50),
        ),
    ]
