# Generated by Django 3.0.3 on 2020-03-11 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200311_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message='Max length is 15 digits.', regex='[0-9]{15}')]),
        ),
    ]
