# Generated by Django 3.0.3 on 2020-03-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200311_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dateofbirth',
        ),
    ]
