# Generated by Django 3.0.3 on 2020-03-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customuser_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics/'),
        ),
    ]
